spring:
  profiles:
    active: ${PROFILE:dev}
  application:
    name: pedido-service
  datasource:
    url: jdbc:h2:mem:pedido;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS PEDIDO
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create

  flyway:
    enabled: false  # Flyway é desabilitado porque geralmente não é usado com bancos de dados em memória

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

cors:
  url: http://localhost:3000

context:
  url: http://localhost:8080

server:
  port: 8080

URL_PRODUTO: http://localhost:8081
URL_CLIENTE: http://localhost:8082