spring:
  profiles:
    active: ${PROFILE:dev}
  application:
    name: pedido-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fastfood
    username: postgres
    password: postgres

  jpa:
    database: Postgresql
    show-sql: true
    open-in-view: false
#    hibernate:
#      ddl-auto: create
  flyway:
    schemas: pedido
    url: jdbc:postgresql://localhost:5432/fastfood
    user: postgres
    password: postgres
    locations: classpath:db/migration
    enabled: true
logging:
  level:
    org:
      flywaydb:
        core=DEBUG:

cors:
  url: http://localhost:3000

context:
  url: http://localhost:8080

server:
  port: 8082