spring:
  application:
    name: pedido-service
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/pedido?currentSchema=pedido
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: Postgresql
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas: pedido
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/pedido?currentSchema=pedido
    user: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

cors:
  url: http://localhost:3000

logging:
  level:
    root: INFO 

