apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pod-pedido-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pod-pedido-api
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 50