apiVersion: v1
kind: Service
metadata:
  name: svc-pedido-api
spec:
  selector:
    app: pod-pedido-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: LoadBalancer