name: Deploy aplicacao pedido

on:
  push:
    branches: [main]


env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: 'us-east-1'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Retrieve AWS Account ID
        id: aws_account
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
          echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV
          echo "Account ID: $ACCOUNT_ID"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Fazendo build do projeto
        run: mvn clean install

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Check if repository exists
        id: check_repo
        run: |
          REPO_NAME="${{ github.repository }}"
          if aws ecr describe-repositories --repository-names "$REPO_NAME" > /dev/null 2>&1; then
            echo "Repository exists: $REPO_NAME"
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "Repository does not exist: $REPO_NAME"
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Create repository if it doesn't exist
        if: env.exists == 'false'
        run: |
          REPO_NAME="${{ github.repository }}"
          aws ecr create-repository --repository-name "$REPO_NAME"
          echo "Created repository: $REPO_NAME"

      - name: Build Docker image
        run: |
          echo "Building Docker image with Account ID: $ACCOUNT_ID"
          docker build -t ${{ github.repository }}:${{ github.sha }} .
          docker tag ${{ github.repository }}:${{ github.sha }} $ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ github.repository }}:latest

      - name: Push Docker image to ECR
        run: |
          echo "Pushing Docker image to $ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"
          docker push $ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ github.repository }}:latest

  deploy:
    name: Deploy to EKS Cluster
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: 'us-east-1'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name fast-food-eks-cluster --region ${{ secrets.AWS_REGION }}

      - name: Apply Kubernetes configurations
        run: |
          kubectl apply -f k8s/config-map-postgres.yaml
          kubectl apply -f k8s/hpa-pedido-api.yaml
          kubectl apply -f k8s/metrics.yaml
          kubectl apply -f k8s/pod-pedido-api.yaml
          kubectl apply -f k8s/svc-pedido-api.yaml

      - name: Update pedido-api image
        run: |
          echo "Updating deployment image to $ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ github.repository }}:latest"
          kubectl set image deployment/pod-pedido-api backend-pedido-api=$ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ github.repository }}:latest